version: '3'

services:
  web:
    build:
      context: ./PaymentSystem/
    volumes:
      - ../PaymentSystem/:/var/www/PaymentSystem
    environment:
      - APP_ENV=dev
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    command: --max_allowed_packet=64M
    ports:
      - "3306:3306"
