version: '3'

services:
  web:
    build:
      context: restaurant-manager-web/
    volumes:
      - ../restaurant-manager-web/:/var/www/restaurant-manager-web
    environment:
      - APP_ENV=dev
    expose:
      - "9001"
    networks:
      test:
        ipv4_address: 10.18.0.3
    depends_on:
      - db

  db:
    image: mysql:8
    volumes:
      - ../mysql-docker:/var/lib/mysql
    environment:
      MYSQL_DATABASE: hokkaido
      MYSQL_USER: hokkaido
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    command: --max_allowed_packet=64M
    ports:
      - "3306:3306"
    networks:
      test:
        ipv4_address: 10.18.0.13

networks:
    test:
      driver: bridge
      ipam:
        config:
          - subnet: 10.18.0.0/16
